apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.25.1
          imagePullPolicy: IfNotPresent
          args: [ "-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml" ]
          ports:
            - containerPort: 9001
          volumeMounts:
            - name: envoy-config
              mountPath: "/run/envoy"
              readOnly: true
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
        - name: user-service
          image: wip/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
        - name: opa
          image: openpolicyagent/opa:1.7.1-envoy-static
          imagePullPolicy: IfNotPresent
          ports:
            - name: opa-envoy
              containerPort: 8182
              protocol: TCP
            - name: opa-api-port
              containerPort: 8181
              protocol: TCP
          args:
            - "run"
            - "--server"
            - "--config-file=/run/opa/opa-config.yaml"
            - "/run/opa/opa-policy.rego"
          volumeMounts:
            - name: backend-opa-policy
              mountPath: /run/opa
              readOnly: true
      volumes:
        - name: envoy-config
          configMap:
            name: user-service-envoy
        - name: backend-opa-policy
          configMap:
            name: user-service-opa-policy-config
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
